# -*- coding: utf-8 -*-
"""aitask4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/196BEI9LiVxz8cM07Komwekdi8416_DJr
"""

import math

class Hexagon:
    def __init__(self, side_length):
        self.side_length = side_length

    def calcArea(self):
        return 1.5 * 1.732 * self.side_length ** 2

    def calcPeri(self):
        return 6 * self.side_length

    def calcAngleSum(self):
        return 6 * 120

    def display(self):
        print("Hexagon:")
        print("Area:", self.calcArea())
        print("Perimeter:", self.calcPeri())
        print("Sum of Angles:", self.calcAngleSum())

class Square:
    def __init__(self, side_length):
        self.side_length = side_length

    def calcAreaSquare(self):
        return self.side_length ** 2

    def calcPeriSquare(self):
        return 4 * self.side_length

    def display(self):
        print("Square:")
        print("Area:", self.calcAreaSquare())
        print("Perimeter:", self.calcPeriSquare())

# Get the last digit of your CNIC
cnic_last_digit = int(input("Enter the last digit of your CNIC: "))

# Create instances of Hexagon and Square classes
hexagon = Hexagon(cnic_last_digit)
square = Square(cnic_last_digit + 1)

while True:
    print("\nMenu:")
    print("1. Hexagon")
    print("2. Square")
    print("3. Exit")

    choice = input("Enter your choice (1, 2, or 3): ")

    if choice == '1':
        hexagon.display()
    elif choice == '2':
        square.display()
    elif choice == '3':
        print("Exiting the program.")
        break
    else:
        print("Invalid choice. Exiting the program.")
        break

